### ISSUE TITLE
Theme for white background environments

### ISSUE THREAD

**Issue by DavidGamba** [konradsz/igrep#15]
Hi, the tools looks super useful!

I was hoping I could use it with my current white background setup. This is how it looks at the moment:
![image](https://user-images.githubusercontent.com/1115287/158610572-49b3975d-7dff-4b6c-9d9f-b7d6a9088f32.png)

Basically, just print the main text as black instead of white.

Maybe by reading the light background flag on neovim?

**Comment by konradsz** [comment]
Hi, thank you for pointing this out, this should definitely be improved. Unfortunately it won't be as easy as setting text color to terminal default, because then the highlight style becomes unreadable. There are two quick solutions - I can either set entire `igrep` background to dark one (will it ruin your UX? 😅) or I can add flag `--light-theme` and choose appropriate colors for it. Proper solution would require me to implement reading config files with user defined theme, but this is a bit more laborious. Which solution would you rather see implemented?

**Comment by DavidGamba** [comment]
Given that I have this in my bash aliases: `alias rg='rg -i --color=always'` I think the flag will do just fine since I'll just add an alias for it too. You don't need to get down the config file rabbit hole unless you really need to.

Thanks so much!
